"""
pipeline/config.py

Central configuration for all pipeline steps.
Override OLLAMA_MODEL via environment variable for demo flexibility:
    OLLAMA_MODEL=gemma4:e4b python pipeline/world_gen.py
"""

import os
from pathlib import Path

# ── Paths ─────────────────────────────────────────────────────────────────────

# Project root is one level above the pipeline/ directory
PROJECT_ROOT     = Path(__file__).parent.parent

ARCHETYPES_DIR   = PROJECT_ROOT / "archetypes"
GENERATED_DIR    = ARCHETYPES_DIR / "generated"
DIALOGUE_DIR     = PROJECT_ROOT / "dialogue"
CHRONICLES_DIR   = PROJECT_ROOT / "chronicles"
FALLBACKS_DIR    = Path(__file__).parent / "fallbacks"

GAME_STATE_FILE   = PROJECT_ROOT / "game_state.json"
WORLD_LORE_FILE   = PROJECT_ROOT / "world_lore.json"
WORLD_REG_FILE    = PROJECT_ROOT / "world_registry.json"
RUMORS_FILE       = PROJECT_ROOT / "rumors.json"

# ── Ollama ────────────────────────────────────────────────────────────────────

OLLAMA_URL   = os.getenv("OLLAMA_URL",   "http://localhost:11434/api/generate")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "gemma4:e4b")

# ── Retry / fallback ──────────────────────────────────────────────────────────

MAX_RETRIES = 3          # LLM call attempts before falling back to pre-generated file
RETRY_DELAY = 2.0        # seconds between retries

# ── World generation ──────────────────────────────────────────────────────────

VARIANTS_PER_ARCHETYPE = 3   # how many variants to generate per NPC role

# ── Archetype roles present in the demo ──────────────────────────────────────

ARCHETYPE_ROLES = ["blacksmith", "innkeeper", "guild_commander"]

# ── Towns in the demo ─────────────────────────────────────────────────────────

TOWNS = {
    "thornwall": {
        "display_name": "Thornwall",
        "roles": ["innkeeper", "blacksmith", "guild_commander"],
    },
    "town_2": {
        "display_name": None,   # generated by world-gen
        "roles": ["innkeeper", "blacksmith"],
    },
}
