"""
pipeline/world_gen.py

World generation pipeline step.
Run once at the start of a new game:

    python pipeline/world_gen.py

What it does:
  1. Prompts for (or generates) the player name
  2. Generates world lore via the LLM (falls back to pre-written file on failure)
  3. Generates 3 NPC variants per archetype role
  4. Randomly assigns one variant per role per town
  5. Writes:
       world_lore.json
       world_registry.json
       archetypes/generated/<role>_<A|B|C>.json
       game_state.json
  6. Runs end_of_day.py to generate day 1 dialogue before the game starts
"""

import json
import logging
import random
import string
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from config import (
    ARCHETYPES_DIR,
    GENERATED_DIR,
    FALLBACKS_DIR,
    GAME_STATE_FILE,
    WORLD_LORE_FILE,
    WORLD_REG_FILE,
    ARCHETYPE_ROLES,
    TOWNS,
    VARIANTS_PER_ARCHETYPE,
    PROJECT_ROOT,
)
from ollama_client import call_ollama_json

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)

VARIANT_LABELS = list(string.ascii_uppercase)


# ── Player name ───────────────────────────────────────────────────────────────

def get_player_name() -> str:
    """
    Read the player name from game_state.json if available,
    otherwise prompt the user. Player can also choose to have
    a name generated by the LLM.
    """
    if GAME_STATE_FILE.exists():
        try:
            data = json.loads(GAME_STATE_FILE.read_text())
            name = data.get("player_name", "").strip()
            if name:
                logger.info("Player name read from game_state.json: %s", name)
                return name
        except (json.JSONDecodeError, KeyError):
            pass

    print("\n── Player Name ──────────────────────────────────────────────")
    print("Enter the hero's name, or press Enter to generate one.")
    choice = input("Name: ").strip()

    if choice:
        return choice

    logger.info("Generating player name via LLM...")
    result = call_ollama_json(
        prompt=(
            "Generate a single fantasy hero name. "
            "Respond ONLY with a JSON object: {\"name\": \"string\"}. "
            "No explanation, no markdown."
        )
    )
    if isinstance(result, dict) and "name" in result:
        generated = str(result["name"])
        print(f"Generated name: {generated}")
        return generated

    fallback = "The Hunter"
    logger.warning("Name generation failed. Using fallback: %s", fallback)
    return fallback


# ── World lore ────────────────────────────────────────────────────────────────

WORLD_LORE_SYSTEM = (
    "You are a world-builder for a fantasy RPG. "
    "You produce concise, atmospheric lore that fits a low-magic monster-hunting setting. "
    "Write in the style of a world companion document, not a novel. "
    "Respond ONLY with valid JSON. No preamble, no explanation, no markdown fences."
)

WORLD_LORE_PROMPT = """
Generate world lore for a fantasy RPG. The world has two towns: Thornwall (a well-established
hunter settlement) and a second, harder eastern town. There is a monster hunting guild.
The main monster type is slimes. Something unknown is stirring in the eastern reach.

Respond ONLY with this exact JSON structure:
{
  "world": {
    "name": "string -- the name of the region",
    "lore_facts": ["string", "string", "string"]
  },
  "towns": {
    "thornwall": {
      "display_name": "Thornwall",
      "lore_facts": ["string", "string", "string"]
    },
    "town_2": {
      "display_name": "string -- generate a name for this eastern town",
      "lore_facts": ["string", "string"]
    }
  }
}

Each lore_fact must be one sentence. Make them varied and atmospheric.
"""


def generate_world_lore() -> dict:
    logger.info("Generating world lore...")
    result = call_ollama_json(prompt=WORLD_LORE_PROMPT, system=WORLD_LORE_SYSTEM)

    if isinstance(result, dict) and "world" in result and "towns" in result:
        logger.info("World lore generated successfully.")
        return result

    logger.warning("World lore generation failed. Loading fallback.")
    return json.loads((FALLBACKS_DIR / "world_lore.json").read_text())


def write_world_lore(lore: dict) -> None:
    output = {"schema_version": "1.0", "generated_day": 0, **lore}
    WORLD_LORE_FILE.write_text(json.dumps(output, indent=2))
    logger.info("Written: %s", WORLD_LORE_FILE)


# ── NPC variant generation ────────────────────────────────────────────────────

NPC_GEN_SYSTEM = (
    "You are generating NPC character profiles for a fantasy RPG. "
    "Follow the constraints in the prompt exactly. "
    "Respond ONLY with valid JSON. No preamble, no explanation, no markdown fences."
)

REQUIRED_VARIANT_FIELDS = {
    "name", "age", "personality", "backstory",
    "personal_detail", "system_prompt_fragment",
}


def load_archetype(role: str) -> dict:
    return json.loads((ARCHETYPES_DIR / f"{role}.json").read_text())


def load_fallback_variant(role: str, label: str) -> dict:
    path = FALLBACKS_DIR / f"{role}_{label}.json"
    if path.exists():
        logger.info("Loading fallback variant: %s_%s", role, label)
        return json.loads(path.read_text())
    logger.warning("Fallback %s_%s not found. Using %s_A.", role, label, role)
    return json.loads((FALLBACKS_DIR / f"{role}_A.json").read_text())


def validate_variant(data: dict) -> bool:
    return REQUIRED_VARIANT_FIELDS.issubset(data.keys())


def generate_variants_for_role(role: str) -> list[dict]:
    archetype = load_archetype(role)
    prompt    = archetype["generation_prompt"]
    variants: list[dict] = []

    for i in range(VARIANTS_PER_ARCHETYPE):
        label = VARIANT_LABELS[i]
        logger.info("Generating %s variant %s...", role, label)

        context = ""
        if variants:
            existing_names = [v["name"] for v in variants]
            context = (
                f"\nThe following names are already taken for this role: "
                f"{', '.join(existing_names)}. Generate someone different."
            )

        result = call_ollama_json(prompt=prompt + context, system=NPC_GEN_SYSTEM)

        if isinstance(result, dict) and validate_variant(result):
            result["role"]       = role
            result["variant_id"] = f"{role}_{label}"
            variants.append(result)
            logger.info("Variant %s_%s generated: %s", role, label, result.get("name"))
        else:
            logger.warning(
                "Variant %s_%s generation failed or invalid. Using fallback.", role, label
            )
            variants.append(load_fallback_variant(role, label))

    return variants


def write_variants(role: str, variants: list[dict]) -> None:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    for i, variant in enumerate(variants):
        out_path = GENERATED_DIR / f"{role}_{VARIANT_LABELS[i]}.json"
        out_path.write_text(json.dumps(variant, indent=2))
        logger.info("Written: %s", out_path)


# ── World registry ────────────────────────────────────────────────────────────

def _make_npc_id(name: str, role: str) -> str:
    """Derive a clean snake_case npc_id from a generated name."""
    raw = name.lower().replace(" ", "_") if name else role
    return "".join(c for c in raw if c.isalnum() or c == "_")


def build_world_registry(all_variants: dict[str, list[dict]], lore: dict) -> dict:
    registry: dict = {"schema_version": "1.0", "towns": {}}

    for town_id, town_cfg in TOWNS.items():
        town_lore    = lore.get("towns", {}).get(town_id, {})
        display_name = town_lore.get("display_name") or town_cfg["display_name"]
        town_entry: dict = {"display_name": display_name, "npcs": {}}

        for role in town_cfg["roles"]:
            variants = all_variants.get(role, [])
            chosen   = random.choice(variants) if variants else load_fallback_variant(role, "A")
            name     = chosen.get("name", role)

            town_entry["npcs"][role] = {
                "archetype":     role,
                "variant_id":    chosen["variant_id"],
                "npc_id":        _make_npc_id(name, role),
                "display_name":  name,
                "first_met_day": None,
            }
            logger.info(
                "Assigned %s -> %s (%s) in %s",
                role, name, chosen["variant_id"], town_id,
            )

        registry["towns"][town_id] = town_entry

    return registry


def write_world_registry(registry: dict) -> None:
    WORLD_REG_FILE.write_text(json.dumps(registry, indent=2))
    logger.info("Written: %s", WORLD_REG_FILE)


# ── Initialise game_state.json ────────────────────────────────────────────────

def initialise_game_state(player_name: str) -> None:
    state = {
        "meta": {"schema_version": "1.0", "day": 1},
        "player_name": player_name,
        "world_state": {
            "monsters_killed_today":   {},
            "monsters_killed_history": [],
        },
        "active_bounties": [],
        "flags": {
            "met_mira":                 False,
            "met_aldric":               False,
            "met_gareth":               False,
            "first_bounty_accepted":    False,
            "first_bounty_completed":   False,
            "player_slept_at_inn":      False,
            "aldric_warned_about_east": False,
        },
        "npc_facts": {},
    }
    GAME_STATE_FILE.write_text(json.dumps(state, indent=2))
    logger.info("Written: %s", GAME_STATE_FILE)


# ── Day 1 dialogue generation ─────────────────────────────────────────────────

def run_initial_dialogue_generation() -> None:
    """
    Run end_of_day.py synchronously so day 1 dialogue is ready
    before the game launches. Blocks until the pipeline finishes.
    """
    script = Path(__file__).parent / "end_of_day.py"

    print("\n── Generating day 1 dialogue ─────────────────────────────────")
    print("  This may take a minute or two...")

    subprocess.run(
        [sys.executable, str(script)],
        cwd=str(PROJECT_ROOT),
    )

    ready   = PROJECT_ROOT / "pipeline_ready.flag"
    failed  = PROJECT_ROOT / "pipeline_failed.flag"
    crashed = PROJECT_ROOT / "pipeline_crashed.flag"

    if ready.exists():
        print("  Day 1 dialogue generated successfully.")
    elif failed.exists():
        print("  Day 1 dialogue generated with warnings (fallback used).")
    elif crashed.exists():
        print("  WARNING: day 1 dialogue generation crashed:")
        print("  " + crashed.read_text()[:300])
        print("  NPCs will use inspector fallback dialogue on day 1.")
    else:
        print("  WARNING: pipeline completed but no flag file was written.")


# ── Entry point ───────────────────────────────────────────────────────────────

def main() -> None:
    print("\n╔══════════════════════════════════════════╗")
    print("║         World Generation Pipeline        ║")
    print("╚══════════════════════════════════════════╝\n")

    if WORLD_REG_FILE.exists() and WORLD_LORE_FILE.exists():
        print("WARNING: world_registry.json and world_lore.json already exist.")
        choice = input("Overwrite and generate a new world? [y/N]: ").strip().lower()
        if choice != "y":
            print("Aborting. No files were changed.")
            return

    # 1. Player name
    player_name = get_player_name()
    logger.info("Hero name: %s", player_name)

    # 2. World lore
    lore = generate_world_lore()
    write_world_lore(lore)

    # 3. NPC variants per archetype role
    all_variants: dict[str, list[dict]] = {}
    for role in ARCHETYPE_ROLES:
        variants = generate_variants_for_role(role)
        write_variants(role, variants)
        all_variants[role] = variants

    # 4. World registry
    registry = build_world_registry(all_variants, lore)
    write_world_registry(registry)

    # 5. Initialise game_state.json
    if GAME_STATE_FILE.exists():
        GAME_STATE_FILE.unlink()
    initialise_game_state(player_name)

    # 6. Generate day 1 dialogue
    run_initial_dialogue_generation()

    # Summary
    print("\n── World generation complete ─────────────────────────────────")
    print(f"  Hero:   {player_name}")
    print(f"  World:  {lore.get('world', {}).get('name', 'Unknown')}")
    for town_id, town in registry["towns"].items():
        print(f"\n  {town['display_name']}:")
        for role, npc in town["npcs"].items():
            print(f"    {role:<20} {npc['display_name']}  ({npc['variant_id']})")
    print()


if __name__ == "__main__":
    main()